routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('layout');
// });
Route::get('/', 'FrontController@index');
Route::post('/', 'FrontController@post');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix'=>'admin', 'middleware'=>['auth',]], function () {
	Route::resource('abouts', 'aboutsController');
	Route::resource('kontaks', 'kontaksController');
	Route::resource('galeris', 'galerisController');
	Route::resource('testimoni', 'testisController');
	Route::resource('partners', 'partnersController');
	Route::resource('feedbacks', 'feedbacksController');
	Route::resource('portofolios', 'portofoliosController');


});

app/galeri.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class galeri extends Model
{
     protected $fillable = ['lokasi', 'keterangan', 'gambar', 'pemberi_tugas','poisis_kontraktor','waktu_pelaksanaan','nomor_kontrak','nilai_kontrak'];
}

app/Http/Controllers/galerisController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use App\galeri;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\File;

class galerisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            $galeris = galeri::select(['id', 'keterangan', 'gambar']);
            return Datatables::of($galeris)
                ->addColumn('action', function($galeri){
                    return view('datatable._action', [
                        'model' => $galeri,
                        'form_url' => route('galeris.destroy', $galeri->id),
                        'edit_url' => route('galeris.edit', $galeri->id),
                        'confirm_message' => 'Yakin mau menghapus ' . $galeri->keterangan . '?'
                    ]);
                })->make(true);
        }

        $html = $htmlBuilder
        ->addColumn(['data' => 'keterangan', 'name'=>'keterangan', 'title'=>'Keterangan'])
        ->addColumn(['data' => 'gambar', 'name'=>'gambar', 'title'=>'Gambar'])
        ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);

        return view('galeris.index')->with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('galeris.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $this->validate($request, [
       'keterangan' => 'required|unique:galeris,keterangan',
       'gambar' => 'image|max:2048'
       ]);

       $galeri = galeri::create($request->except('gambar'));
       
       // isi field cover jika ada cover yang diupload
       if ($request->hasFile('gambar')) {
       
       // Mengambil file yang diupload
       $uploaded_gambar = $request->file('gambar');
       
       // mengambil extension file
       $extension = $uploaded_gambar->getClientOriginalExtension();
       
       // membuat nama file random berikut extension
       $filename = md5(time()) . '.' . $extension;
       
       // menyimpan cover ke folder public/img
       $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'galeri';
       $uploaded_gambar->move($destinationPath, $filename);
       
       // mengisi field cover di book dengan filename yang baru dibuat
       $galeri->gambar = $filename;
       $galeri->save();
       }
       
       Session::flash("flash_notification", [
        "level"=>"success",
        "message"=>"Berhasil menyimpan gambar $galeri->keterangan"
       ]);
       
       return redirect()->route('galeris.index');
       }
    


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $galeri = galeri::find($id);
        return view('galeris.edit')->with(compact('galeri'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $this->validate($request, [
                   'keterangan' => 'required|unique:galeris,keterangan,' . $id,
                   'gambar' => 'image|max:2048'
               ]);
               
               $galeri = galeri::find($id);
               $galeri->update($request->all());
               
               if ($request->hasFile('gambar')) {
               // menambil cover yang diupload berikut ekstensinya
                   $filename = null;
                   $uploaded_gambar = $request->file('gambar');
                   $extension = $uploaded_gambar->getClientOriginalExtension();
               
               // membuat nama file random dengan extension
                   $filename = md5(time()) . '.' . $extension;
                   $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'galeri';
               
               // memindahkan file ke folder public/img
                   $uploaded_gambar->move($destinationPath, $filename);
               
               // hapus cover lama, jika ada
                   if ($galeri->gambar) {
                   $old_gambar = $galeri->gambar;
                   $filepath = public_path() . DIRECTORY_SEPARATOR . 'img'
                       . DIRECTORY_SEPARATOR . $galeri->gambar;
               
                   try {
                       File::delete($filepath);
                   } catch (FileNotFoundException $e) {
               // File sudah dihapus/tidak ada
                   }
               }
               // ganti field cover dengan cover yang baru
                   $galeri->gambar = $filename;
                   $galeri->save();
               }
               
               Session::flash("flash_notification", [
                   "level"=>"success",
                   "message"=>"Berhasil menyimpan $galeri->keterangan"
               ]);
               
               return redirect()->route('galeris.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $galeri = galeri::find($id);
        
        // hapus cover lama, jika ada
        if ($galeri->gambar) {
        $old_gambar = $galeri->gambar;
        $filepath = public_path() . DIRECTORY_SEPARATOR . 'galeri'
        . DIRECTORY_SEPARATOR . $galeri->gambar;
        
        try {
        File::delete($filepath);
        } catch (FileNotFoundException $e) {
        // File sudah dihapus/tidak ada
        }
        }
        
        $galeri->delete();
        
        Session::flash("flash_notification", [
        "level"=>"success",
        "message"=>"Gambar berhasil dihapus"
        ]);
        return redirect()->route('galeris.index');
    }
}

resources/views/galeris/_form.blade.php
<div class="form-group{{ $errors->has('keterangan') ? ' has-error' : '' }}">
	{!! Form::label('keterangan', 'Keterangan', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('keterangan', null, ['class'=>'form-control']) !!}
	{!! $errors->first('keterangan', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('lokasi') ? ' has-error' : '' }}">
	{!! Form::label('lokasi', 'Lokasi', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('lokasi', null, ['class'=>'form-control']) !!}
	{!! $errors->first('lokasi', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('pemberi_tugas') ? ' has-error' : '' }}">
	{!! Form::label('pemberi_tugas', 'Pemberi Tugas', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('pemberi_tugas', null, ['class'=>'form-control']) !!}
	{!! $errors->first('pemberi_tugas', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('posisi_kontraktor') ? ' has-error' : '' }}">
	{!! Form::label('posisi_kontraktor', 'Posisi Kontraktor', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('posisi_kontraktor', null, ['class'=>'form-control']) !!}
	{!! $errors->first('posisi_kontraktor', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('nomor_kontrak') ? ' has-error' : '' }}">
	{!! Form::label('nomor_kontrak', 'Nomor Kontrak', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('nomor_kontrak', null, ['class'=>'form-control']) !!}
	{!! $errors->first('nomor_kontrak', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('nilai_kontrak') ? ' has-error' : '' }}">
	{!! Form::label('nilai_kontrak', 'Nilai Kontrak', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('nilai_kontrak', null, ['class'=>'form-control']) !!}
	{!! $errors->first('nilai_kontrak', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('waktu_pelaksanaan') ? ' has-error' : '' }}">
	{!! Form::label('waktu_pelaksanaan', 'Waktu Pelaksanaan', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('waktu_pelaksanaan', null, ['class'=>'form-control']) !!}
	{!! $errors->first('waktu_pelaksanaan', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('gambar') ? ' has-error' : '' }}">
	{!! Form::label('gambar', 'Gambar', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::file('gambar') !!}
		@if (isset($galeri) && $galeri->gambar)
		<p>
		{!! Html::image(asset('galeri/'.$galeri->gambar), null, ['class'=>'img-rounded img-responsive']) !!}
		</p>
		@endif
		{!! $errors->first('gambar', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
<div class="col-md-4 col-md-offset-2">
{!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
</div>
</div>

resources/views/galeris/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/galeris') }}">Galeri</a></li>
					<li class="active">Tambah Gambar</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Tambah Gambar</h2>
					</div>

					<div class="panel-body">
						{!! Form::open(['url' => route('galeris.store'),
							'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
							@include('galeris._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/galeris/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/galeris') }}">Galeri</a></li>
					<li class="active">Ubah Gambar</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Ubah Gambar</h2>
					</div>

					<div class="panel-body">
						{!! Form::model($galeri, ['url' => route('galeris.update', $galeri->id),
							'method' => 'put', 'files'=>'true', 'class'=>'form-horizontal']) !!}
						@include('galeris._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>	
	</div>
@endsection

resources/views/galeris/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="active">Galeri</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Galeri</h2>
					</div>
	
					<div class="panel-body">
						<p> <a class="btn btn-primary" href="{{ url('/admin/galeris/create') }}">Tambah</a></p>
						{!! $html->table(['class'=>'table-striped']) !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
{!! $html->scripts() !!}
@endsection