routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('layout');
// });
Route::get('/', 'FrontController@index');
Route::post('/', 'FrontController@post');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix'=>'admin', 'middleware'=>['auth',]], function () {
	Route::resource('abouts', 'aboutsController');
	Route::resource('kontaks', 'kontaksController');
	Route::resource('galeris', 'galerisController');
	Route::resource('testimoni', 'testisController');
	Route::resource('partners', 'partnersController');
	Route::resource('feedbacks', 'feedbacksController');
	Route::resource('portofolios', 'portofoliosController');


});

app/partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class partner extends Model
{
    protected $fillable = ['nama_perusahaan', 'logo'];
}

app/Http/Controllers/partnersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use App\partner;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\File;

class partnersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function index(Request $request, Builder $htmlBuilder)
           {
               if ($request->ajax()) {
               $partners = partner::select(['id', 'nama_perusahaan', 'logo']);
               return Datatables::of($partners)
                ->addColumn('action', function($partner){
                    return view('datatable._action', [
                        'model' => $partner,
                        'form_url' => route('partners.destroy', $partner->id),
                        'edit_url' => route('partners.edit', $partner->id),
                        'confirm_message' => 'Yakin mau menghapus logo ' . $partner->nama_perusahaan . '?'
                        ]);
                    })->make(true);
               }
           
               $html = $htmlBuilder
                   ->addColumn(['data' => 'nama_perusahaan', 'name'=>'nama_perusahaan', 'title'=>'Nama Perusahaan'])
                   ->addColumn(['data' => 'logo', 'name'=>'logo', 'title'=>'Logo'])
                   ->addColumn(['data' => 'action', 'name'=>'action', 'title'=>'', 'orderable'=>false, 'searchable'=>false]);
               
               return view('partners.index')->with(compact('html'));
           }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
   public function create()
       {
          return view('partners.create');
       }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_perusahaan' => 'required|unique:partners,nama_perusahaan',
            'logo' => 'image|max:2048'
        ]);
    
        $partner = partner::create($request->except('logo'));
        
        // isi field cover jika ada cover yang diupload
        if ($request->hasFile('logo')) {
        // Mengambil file yang diupload
        $uploaded_logo = $request->file('logo');
            // mengambil extension file
            $extension = $uploaded_logo->getClientOriginalExtension();
        
            // membuat nama file random berikut extension
            $filename = md5(time()) . '.' . $extension;
        
            // menyimpan cover ke folder public/img
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'logo';
            $uploaded_logo->move($destinationPath, $filename);
            
            // mengisi field cover di book dengan filename yang baru dibuat
            $partner->logo = $filename;
            $partner->save();
        }
        
        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menyimpan logo $partner->nama_perusahaan"
        ]);
        
        return redirect()->route('partners.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $partner = partner::find($id);
        return view('partners.edit')->with(compact('partner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   public function update(Request $request, $id)
       {
          $this->validate($request, [
                      'nama_perusahaan' => 'required|unique:partners,nama_perusahaan,' . $id,
                      'logo' => 'image|max:2048'
                  ]);
                  
                  $partner = partner::find($id);
                  $partner->update($request->all());
                  
                  if ($request->hasFile('logo')) {
                  // menambil cover yang diupload berikut ekstensinya
                      $filename = null;
                      $uploaded_logo = $request->file('logo');
                      $extension = $uploaded_logo->getClientOriginalExtension();
                  
                  // membuat nama file random dengan extension
                      $filename = md5(time()) . '.' . $extension;
                      $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'logo';
                  
                  // memindahkan file ke folder public/img
                      $uploaded_logo->move($destinationPath, $filename);
                  
                  // hapus cover lama, jika ada
                      if ($partner->logo) {
                      $old_logo = $partner->logo;
                      $filepath = public_path() . DIRECTORY_SEPARATOR . 'logo'
                          . DIRECTORY_SEPARATOR . $partner->logo;
                  
                      try {
                          File::delete($filepath);
                      } catch (FileNotFoundException $e) {
                  // File sudah dihapus/tidak ada
                      }
                  }
                  // ganti field cover dengan cover yang baru
                      $partner->logo = $filename;
                      $partner->save();
                  }
                  
                  Session::flash("flash_notification", [
                      "level"=>"success",
                      "message"=>"Berhasil menyimpan logo $partner->nama_perusahaan"
                  ]);
                  
                  return redirect()->route('partners.index');
       }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $partner = partner::find($id);
    
        // hapus cover lama, jika ada
        if ($partner->logo) {
            $old_logo = $partner->logo;
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'logo'
                . DIRECTORY_SEPARATOR . $partner->logo;
    
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
    // File sudah dihapus/tidak ada
        }
    }
    $partner->delete();
    
    Session::flash("flash_notification", [
        "level"=>"success",
        "message"=>"Logo berhasil dihapus"
    ]);
    
    return redirect()->route('partners.index');
    }
}

resources/views/partners/_form.blade.php
<div class="form-group{{ $errors->has('nama_perusahaan') ? ' has-error' : '' }}">
	{!! Form::label('nama_perusahaan', 'Nama Perusahaan', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
	{!! Form::text('nama_perusahaan', null, ['class'=>'form-control']) !!}
	{!! $errors->first('nama_perusahaan', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('logo') ? ' has-error' : '' }}">
	{!! Form::label('logo', 'Logo', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::file('logo') !!}
		@if (isset($partner) && $partner->logo)
		<p>
		{!! Html::image(asset('logo/'.$partner->logo), null, ['class'=>'img-rounded img-responsive']) !!}
		</p>
		@endif
		{!! $errors->first('logo', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
<div class="col-md-4 col-md-offset-2">
{!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
</div>
</div>

resources/views/partners/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/partners') }}">Partner</a></li>
					<li class="active">Tambah Partner</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Tambah Partner</h2>
					</div>

					<div class="panel-body">
						{!! Form::open(['url' => route('partners.store'),
							'method' => 'post', 'files'=>'true', 'class'=>'form-horizontal']) !!}
							@include('partners._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/partners/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/partner') }}">Partner</a></li>
					<li class="active">Ubah Partner</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Ubah Partner</h2>
					</div>
				
					<div class="panel-body">
						{!! Form::model($partner, ['url' => route('partners.update', $partner->id),
							'method' => 'put', 'files'=>'true', 'class'=>'form-horizontal']) !!}
						@include('partners._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/partners/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="active">Partner</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Partner</h2>
					</div>

					<div class="panel-body">
						<p> <a class="btn btn-primary" href="{{ url('/admin/partners/create') }}">Tambah</a></p>
						{!! $html->table(['class'=>'table-striped']) !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
{!! $html->scripts() !!}
@endsection