routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', function () {
//     return view('layout');
// });
Route::get('/', 'FrontController@index');
Route::post('/', 'FrontController@post');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['prefix'=>'admin', 'middleware'=>['auth',]], function () {
	Route::resource('abouts', 'aboutsController');
	Route::resource('kontaks', 'kontaksController');
	Route::resource('galeris', 'galerisController');
	Route::resource('testimoni', 'testisController');
	Route::resource('partners', 'partnersController');
	Route::resource('feedbacks', 'feedbacksController');
	Route::resource('portofolios', 'portofoliosController');


});

resources/views/testimoni/_form.blade.php
<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
	{!! Form::label('nama', 'Nama', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::text('nama', null, ['class'=>'form-control']) !!}
		{!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('jabatan') ? ' has-error' : '' }}">
	{!! Form::label('jabatan', 'Jabatan', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::text('jabatan', null, ['class'=>'form-control']) !!}
		{!! $errors->first('jabatan', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('jabatan') ? ' has-error' : '' }}">
	{!! Form::label('testi', 'Testi', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::text('testi', null, ['class'=>'form-control']) !!}
		{!! $errors->first('testi', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group{{ $errors->has('foto') ? ' has-error' : '' }}">
	{!! Form::label('foto', 'Foto', ['class'=>'col-md-2 control-label']) !!}
	<div class="col-md-4">
		{!! Form::file('foto') !!}
		@if (isset($testi) && $testi->foto)
		<p>
		{!! Html::image(asset('testi/'.$testi->foto), null, ['class'=>'img-rounded img-responsive']) !!}
		</p>
		@endif
		{!! $errors->first('foto', '<p class="help-block">:message</p>') !!}
	</div>
</div>

<div class="form-group">
	<div class="col-md-4 col-md-offset-2">
		{!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
	</div>
</div>


		
		


		
		

resources/views/testimoni/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/testimoni') }}">Testi</a></li>
					<li class="active">Tambah Testi</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Tambah Testi</h2>
					</div>

					<div class="panel-body">
						{!! Form::open(['url' => route('testimoni.store'),
						'method' => 'post', 'class'=>'form-horizontal']) !!}
						@include('testimoni._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/testimoni/edit.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ url('/admin/testimoni') }}">Testi</a></li>
					<li class="active">Ubah Testi</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Ubah Testi</h2>
					</div>

					<div class="panel-body">
						{!! Form::model($testi, ['url' => route('testimoni.update', $testi->id),
							'method'=>'put', 'class'=>'form-horizontal']) !!}
						@include('testimoni._form')
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/testimoni/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="active">Testi</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Testi</h2>
					</div>

					<div class="panel-body">
						<p> <a class="btn btn-primary" href="{{ route('testimoni.create') }}">Tambah</a> </p>
						{!! $html->table(['class'=>'table-striped']) !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('scripts')
{!! $html->scripts() !!}
@endsection